- cdkworkshop.com/cdkworkshop.com.ts
- cdkworkshop.com/package-lock.json
- cdkworkshop.com/package.json
Updated CDK framework to 0.19.0
> Updated to CDK 0.19.0

- workshop/content/40-hit-counter/200-handler.md
> chore: Update 200-handler.md

- workshop/content/40-hit-counter/300-resources.md
Changed "add the following code" to "add the following highlighted code".
> chore: Update 300-resources.md

- workshop/content/40-hit-counter/400-use.md
Added "the following highlighted code".
> chore: Update 400-use.md

- workshop/content/40-hit-counter/500-logs.md
The CloudWatch console changed.
> chore: Update 500-logs.md

- workshop/content/40-hit-counter/600-permissions.md
> chore: Update 600-permissions.md

- workshop/content/40-hit-counter/700-test.md
Added a few interim steps for those who aren't familiar with the console; added a step to hit a new path and see a new table item.
> chore: Update 700-test.md

- workshop/content/50-table-viewer/400-expose-table.md
Added blurb about closing npm run watch command.
> chore: Update 400-expose-table.md

- workshop/content/50-table-viewer/500-deploy.md
> chore: Update 500-deploy.md

- workshop/content/50-table-viewer/300-add.md
> chore: Update 300-add.md

- cdkworkshop.com/cdkworkshop.com.ts
- cdkworkshop.com/guardduty.ts
- cdkworkshop.com/package-lock.json
- cdkworkshop.com/package.json
- workshop/content/15-prerequisites/200-account.md
- workshop/content/15-prerequisites/300-nodejs.md
- workshop/content/15-prerequisites/500-toolkit.md
- workshop/content/20-create-project/100-cdk-init.md
- workshop/content/20-create-project/200-watch.md
- workshop/content/20-create-project/400-synth.md
- workshop/content/20-create-project/500-deploy.md
- workshop/content/30-hello-cdk/100-cleanup.md
- workshop/content/30-hello-cdk/200-lambda.md
- workshop/content/30-hello-cdk/300-apigw.md
- workshop/content/40-hit-counter/300-resources.md
- workshop/content/40-hit-counter/400-use.md
- workshop/content/40-hit-counter/600-permissions.md
- workshop/content/40-hit-counter/700-test.md
- workshop/content/50-table-viewer/200-install.md
- workshop/content/50-table-viewer/500-deploy.md
- workshop/content/60-cleanups/_index.md
- workshop/themes/learn/README.md
1. Use `aws-cdk@^0.22.0` for infrastructure provisioning
2. Normalize console "code frames" to use `console` formatter
+ Only use `$` prefix when commands & output are mixed
3. Use Route53 A record construct
> Misc. improvements

- workshop/content/30-hello-cdk/100-cleanup.md
NA
Corrected typo in tutorial text. Changed begin -> being
> corrected typo in clean-up tutorial text

- cdkworkshop.com/cdkworkshop.com.ts
Otherwise the resource will be replaced and that's impossible.
> fix: preserve logical ID of DNS record resource

- workshop/content/15-prerequisites/500-toolkit.md
- workshop/content/15-prerequisites/_index.md
- workshop/content/20-create-project/100-cdk-init.md
- workshop/content/40-hit-counter/_index.md
- workshop/content/70-conclusion/_index.md
- workshop/content/_index.md
Fixed bad links in 70-conclusion/_index.md; added new links to other pages.
Added "See Also" section where appropriate.
> chore (docs): added links and updated existing links

- workshop/content/60-cleanups/_index.md
> Addressed typo ('chargers' to 'charges')

- LICENSE
- workshop/config.toml
- workshop/content/15-prerequisites/100-awscli.md
- workshop/content/15-prerequisites/500-toolkit.md
- workshop/content/15-prerequisites/_index.md
- workshop/content/20-create-project/100-cdk-init.md
- workshop/content/20-create-project/300-structure.md
- workshop/content/20-create-project/400-synth.md
- workshop/content/30-hello-cdk/100-cleanup.md
- workshop/content/30-hello-cdk/200-lambda.md
- workshop/content/30-hello-cdk/300-apigw.md
- workshop/content/40-hit-counter/100-api.md
- workshop/content/40-hit-counter/300-resources.md
- workshop/content/40-hit-counter/400-use.md
- workshop/content/40-hit-counter/600-permissions.md
- workshop/content/50-table-viewer/200-install.md
- workshop/content/50-table-viewer/300-add.md
- workshop/content/50-table-viewer/400-expose-table.md
- workshop/content/70-conclusion/_index.md
- workshop/layouts/partials/menu-footer.html
Updates typescript code for 0.39.0
Fixes some typos
Adds social media links
> fix: litovng/update 0.39.0

- workshop/content/20-typescript/40-hit-counter/600-permissions.md
- workshop/content/20-typescript/50-table-viewer/_index.md
TypeScript workshop: Updated highlighting lines for two pages to properly highlight the permissions changes necessary.  Also updated href for tableviewer image.
> Fixed highlighting issue in TypeScript troubleshooting for permissions.

- workshop/content/30-python/40-hit-counter/400-use.md
*Description of changes:* Previously referencing TypeScript file, updated to reference python equivalent as this is the python learning path.
> Fixed reference to TypeScript file

- workshop/content/30-python/50-table-viewer/300-add.md
*Description of changes:* Reference to typescript file changed to Python equivalent
> Changed TypeScript reference to Python

- workshop/content/_index.md
Updated broken link to official AWS CDK API Reference
> Fixed broken link to CDK API Reference

- workshop/config.toml
The gitter url in the menu is invalid.
> Update the gitter url

- workshop/content/30-python/50-table-viewer/400-expose-table.md
*Description of changes:* Two locations where Typescript files were references, updated to python equivalent.
> Updated reference to TypeScript files

- workshop/content/30-python/40-hit-counter/300-resources.md
*Description of changes:* Previous PR updated this but I had missed the definition of the Property earlier in the file which was actually causing this issue.
> Reverting Change due to missing Property

- workshop/content/30-python/40-hit-counter/600-permissions.md
> Refer to singular "line" since we're only adding one line

- workshop/content/30-python/40-hit-counter/600-permissions.md
> Python code should use Python highlighting

- workshop/content/30-python/50-table-viewer/200-install.md
> Note that the output shown is only last 2 lines of more

- workshop/content/30-python/40-hit-counter/500-logs.md
> Update instruction to match button name in screenshot

- workshop/content/30-python/40-hit-counter/300-resources.md
Also remove redundant use of "Now" to introduce the code. Set syntax coloring to use Python.
---
> Adjust highlighting to cover all new code to be added

- workshop/content/30-python/30-hello-cdk/300-apigw.md
> Add note about what file you should be editing

- .mergify.yml
Updates the mergify YAML to be proper valid YAML to YAML parsers
Fixes #75 
---
> fix: Use proper YAML syntax for the mergify config

- workshop/content/30-python/30-hello-cdk/100-cleanup.md
- workshop/content/30-python/30-hello-cdk/300-apigw.md
Updating some documentation based on feedback of running through the python cdk example.
Fixes #73 
---
> fix: Update workshop documentation due to syntax nuances

- workshop/content/20-typescript/40-hit-counter/100-api.md
> fix: improve description in the Typescript Workshop

- workshop/content/40-dotnet/30-hello-cdk/300-apigw.md
> chore: typo sharp

- workshop/content/20-typescript/20-create-project/100-cdk-init.md
Updated the output of the `cdk init` command to reflect the current output (which has changed somewhat from the original version).
> docs: Updated 'cdk init' output

- code/csharp/src/CdkWorkshop/HitCounter.cs
- workshop/content/20-typescript/40-hit-counter/300-resources.md
- workshop/content/30-python/20-create-project/100-cdk-init.md
- workshop/content/30-python/20-create-project/300-structure.md
- workshop/content/30-python/40-hit-counter/600-permissions.md
- workshop/content/30-python/50-table-viewer/500-deploy.md
- workshop/content/40-dotnet/50-table-viewer/400-expose-table.md
- resolve C# Table vs MyTable diff (#123)
- hitcounter to hitcount typo fix (#129)
- changed some wording to clarify cdk-workshop vs hello declarations in py (#102)
- add alternative link to table viewer source (#47)
Fixes #123 
Fixes #129 
Fixes #102 
Fixes #47 (finally)
---
> fix: multiple small bug fixes across workshops

- .github/workflows/close-stale-issues.yml
Running once a day at 6 UTC instead of every hour.
> chore(repo): Update stale action cron to run once a day at 6 utc

- cdkworkshop.com/cdkworkshop.com.ts
- cdkworkshop.com/package-lock.json
- cdkworkshop.com/package.json
Upgrade CDK in preparation of making a pipeline for this project.
---
> chore: upgrade CDK to 1.56.0

- cdkworkshop.com/cdk.json
- cdkworkshop.com/cdkworkshop.com.ts
- cdkworkshop.com/package-lock.json
- cdkworkshop.com/package.json
- cdkworkshop.com/pipeline.ts
> feat: add Pipeline

- workshop/layouts/partials/menu-footer.html
Updates menu-footer to include Privacy and site terms links and use latest copyright
---
> fix: update menu-footer compliance

- workshop/content/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.md
> fix: replace deprecated inline with fromInline

- workshop/content/20-typescript/70-advanced-topics/200-pipelines/5000-test-actions.md
- workshop/content/40-dotnet/70-advanced-topics/100-pipelines/5000-test-actions.md
Fix typo in Polish Pipeline section Typescript and .NET Workshops
Fixes #181 
---
> fix: typo congratulations

- workshop/content/20-typescript/30-hello-cdk/200-lambda.md
This is minor suggestion if the user is using git.
Fixes # 
---
> fix: added a suggestion on `!lambda/*.js`

- workshop/content/40-dotnet/70-advanced-topics/100-pipelines/3000-new-pipeline.md
I worked through the c# workshop advanced topics and ran into some issues deploying the pipeline. I have amended the docs for future workshop attendees. 
Since the changes were small I did not create an issue.
---
> docs: fix synth action commands in c# workshop

- workshop/content/20-typescript/70-advanced-topics/200-pipelines/4000-build-stage.md
> fix: sample code property name is not correct.

- workshop/content/20-typescript/70-advanced-topics/200-pipelines/4000-build-stage.md
Fixes:
- Variable name in typescript pipelines example
---
> fix: fix variable name in typescript pipelines

- code/typescript/main-workshop/lib/cdk-workshop-stack.ts
- code/typescript/pipelines-workshop/lib/cdk-workshop-stack.ts
- code/typescript/tests-workshop/lib/cdk-workshop-stack.ts
- workshop/content/20-typescript/70-advanced-topics/200-pipelines/4000-build-stage.md
- workshop/content/20-typescript/70-advanced-topics/200-pipelines/5000-test-actions.md
The change in #200 fixed some typos, but inadvertently broke the build by only
fixing some of the instances. This cleans up the code to match.
---
> chore: fix more typos

- code/typescript/main-workshop/package-lock.json
- code/typescript/main-workshop/package.json
Honestly not exactly sure why it didn't work before. Pretty sure I
tested it. Tested it again now, let's see what this does.
Fixes the broken canary.
Fixes # 
---
> chore: fiddle with the lockfile a little more to make the build succeed

- cdkworkshop.com/cdkworkshop.com.ts
> chore: enable termination protection

- workshop/content/20-typescript/70-advanced-topics/100-construct-testing/_index.md
- workshop/content/70-conclusion/_index.md
> chore: fix incorrect links

- cdkworkshop.com/package.json
- workshop/data/common.toml
> chore: update cdk version

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/guidance.yml
This PR:
- Removes unsupported emoji escape codes from the issue name.
- Removes unintentional newlines in question descriptions.
---
> fix(github issues v2): removed unsupported emojis and removed unintentional newline spacing.

- .github/workflows/auto-merge.yml
> chore: update workflow

- .github/workflows/auto-merge.yml
- .github/workflows/pr-comment.yml
- .github/workflows/semantic-fails.yml
> chore: add missing 'steps' and add additional triggers to automerge

- .github/workflows/pr-comment.yml
> chore: missing 'runs-on' in workflow

- cdkworkshop.com/cdkworkshop.com.ts
- cdkworkshop.com/guardduty.ts
- cdkworkshop.com/package-lock.json
- cdkworkshop.com/package.json
- cdkworkshop.com/pipeline.ts
This upgrades the CDK Workshop _CDK Application_ to use CDKv2. Note that this
doesn't actually update any of the content in the workshop, just the underlying
application itself. A future PR will update the workshop content itself.
---
> chore: upgrade CDK application to use CDK v2

- workshop/content/30-python/70-advanced-topics/100-construct-testing/1000-assertion-test.md
- workshop/content/30-python/70-advanced-topics/100-construct-testing/2000-validation-tests.md
- workshop/content/30-python/70-advanced-topics/100-construct-testing/_index.md
adding a new testing section to the advanced topics that matches the
testing section of the typescript workshop
---
> feat(testing-workshop): add testing workshop for python

- workshop/content/50-java/70-advanced-topics/100-construct-testing/1000-assertion-test.md
- workshop/content/50-java/70-advanced-topics/100-construct-testing/2000-validation-tests.md
- workshop/content/50-java/70-advanced-topics/100-construct-testing/_index.md
adding a new testing section to the advanced topics that matches the
testing section of the typescript workshop
---
> feat(testing-workshop): add testing workshop for java

- workshop/content/30-python/20-create-project/200-virtualenv.md
> fix: fixed typo python docs 200-virtualenv.md

- code/typescript/main-workshop/package-lock.json
- code/typescript/main-workshop/package.json
- code/typescript/pipelines-workshop/package-lock.json
- code/typescript/pipelines-workshop/package.json
- code/typescript/tests-workshop/package-lock.json
- code/typescript/tests-workshop/package.json
Fixes security issue dependabot couldn't fix
---
> chore: update cdk versions

- workshop/content/20-typescript/70-advanced-topics/200-pipelines/4000-build-stage.md
Remove the incorrectly highlighted line of code
Fixes #552 
---
> Unhighlight unchanged line

- workshop/content/60-construct-hub/_index.md
Just a small typo
Fixes # 
---
> chore: typo in Construct Hub

- workshop/content/15-prerequisites/300-nodejs.md
- workshop/content/15-prerequisites/_index.md
> fix: clear up language prerequisite requirements

- workshop/content/20-typescript/20-create-project/500-deploy.md
- workshop/content/30-python/20-create-project/500-deploy.md
- workshop/content/40-dotnet/20-create-project/500-deploy.md
- workshop/content/50-java/20-create-project/500-deploy.md
> fix: clear up security change description

- workshop/content/20-typescript/30-hello-cdk/200-lambda.md
> fix: add clearer section on gitignore with lambda in ts section

- workshop/content/20-typescript/70-advanced-topics/200-pipelines/3000-new-pipeline.md
- workshop/content/20-typescript/70-advanced-topics/200-pipelines/4000-build-stage.md
- workshop/content/30-python/70-advanced-topics/200-pipelines/4000-build-stage.md
- workshop/content/50-java/70-advanced-topics/100-pipelines/4000-build-stage.md
> Fix wrong npm repo and typo

- workshop/content/20-typescript/_index.md
- workshop/content/30-python/_index.md
- workshop/content/40-dotnet/_index.md
- workshop/content/50-java/_index.md
> fix: broken link references break build

- workshop/content/20-typescript/_index.md
- workshop/content/30-python/_index.md
- workshop/content/40-dotnet/_index.md
- workshop/content/50-java/_index.md
> fix: broken link in live build

- cdkworkshop.com/cdkworkshop.com.ts
- cdkworkshop.com/package-lock.json
- Migrated the distribution to the new Distribution contruct
- Added security headers to client responses
---
> feat: migrate cf distribution new construct

- cdkworkshop.com/cdkworkshop.com.ts
Fixes issue preventing us from adding headers
---
> override distribution logical id to prevent recreation

- cdkworkshop.com/package-lock.json
> fix: package-lock misformatted

- cdkworkshop.com/cdkworkshop.com.ts
> fix: add inline script/style shas

- cdkworkshop.com/cdkworkshop.com.ts
> fix: add additional inline style hash

- cdkworkshop.com/cdkworkshop.com.ts
> fix: CSP policy

- cdkworkshop.com/cdkworkshop.com.ts
This adds a lambda handler to the cloudfront distribution, allowing /ja/ -> /ja/index.html
Additionally, fonts were being discarded due to a small bug in my csp headers. Whoops.
---
> Fix index.html not being served from subdirectories, font load issues

- cdkworkshop.com/cdkworkshop.com.ts
- workshop/assets/js/ga-shortbread.js
- workshop/layouts/partials/custom-footer.html
- workshop/layouts/partials/docs/inject/footer.html
https://twitter.com/TomKellerAWS/status/1603431432399237122
---
> fix: disable shortbread

- workshop/content/japanese/20-typescript/70-advanced-topics/200-pipelines/5000-test-actions.md
> fix highlight in Japanese typescript pipeline test doc

- workshop/content/japanese/20-typescript/70-advanced-topics/200-pipelines/4000-build-stage.md
> fix dirname

- workshop/content/english/40-dotnet/70-advanced-topics/100-pipelines/5000-test-actions.md
to align with previous step and the api.  Is `AddApplicationStage` from a previous version?
Fixes #818
> Update AddApplicationStage to AddStage

- workshop/content/english/30-python/70-advanced-topics/200-pipelines/3000-new-pipeline.md
- workshop/content/english/30-python/70-advanced-topics/200-pipelines/5000-test-actions.md
- workshop/content/japanese/30-python/50-table-viewer/300-add.md
- workshop/content/japanese/30-python/70-advanced-topics/200-pipelines/3000-new-pipeline.md
- workshop/content/japanese/30-python/70-advanced-topics/200-pipelines/4000-build-stage.md
- workshop/content/japanese/30-python/70-advanced-topics/200-pipelines/5000-test-actions.md
> Fix python code description

- .github/workflows/handle-stale-discussions.yml
> (chore): added stale discussions workflow

- workshop/content/english/15-prerequisites/200-account.md
> Rectified the numbering

- workshop/assets/css/style.scss
- workshop/content/english/20-typescript/50-table-viewer/200-install.md
- workshop/content/english/30-python/50-table-viewer/200-install.md
- workshop/content/english/40-dotnet/50-table-viewer/200-install.md
- workshop/content/english/50-java/50-table-viewer/200-install.md
- workshop/content/english/50-java/50-table-viewer/_index.md
- workshop/content/english/60-go/50-table-viewer/200-install.md
- workshop/content/japanese/20-typescript/50-table-viewer/200-install.md
- workshop/content/japanese/30-python/50-table-viewer/200-install.md
- workshop/content/japanese/40-dotnet/50-table-viewer/200-install.md
- workshop/content/japanese/50-java/50-table-viewer/200-install.md
- workshop/content/japanese/50-java/50-table-viewer/_index.md
- workshop/content/japanese/60-go/50-table-viewer/200-install.md
- workshop/layouts/shortcodes/nextprevlinks.html
- Bump CDK Dynamo Table Viewer dependency.
- Use CSS class for Prev/Next links rendered for a section.
Fixes #1139
Fixes #1231
---
> feat: Bump CDK Dynamo Table Viewer dependency.
