- workshop/content/40-hit-counter/100-api.md
Let user know to expect an error when they save hitcounter.ts before we use props.
Added warning when they save hitcounter.ts before it uses props.
> chore: Update 100-api.md

- workshop/content/30-hello-cdk/200-lambda.md
Removed warning to Windows users about running "npm install @aws-cdk/aws-*" when "npm run watch" is running in another window.
I need someone else to confirm. If the warning is no longer valid, we also need to remove it from:
- 30-hello-cdk/300-apigw.md
- 40-hit-counter/300-resources.md
- 50-table-viewer/200-install.md
> chore: Update 200-lambda.md

- workshop/content/40-hit-counter/500-logs.md
Indented with 4 spaces, they are rendered as inline code blocks, which
prevents the image to be referenced. Reduced the indent to 3 spaces
(matching the surroundings) fixes that.
Also fixed the numbered points syntax so they render correctly.
> fix: Over-indented image references

- workshop/content/15-prerequisites/400-ide.md
Add `emacs` with `tide-mode` to IDE page.  (I've been using it in the workshop with excellent results.)
As far as testing goes, I did an `npm run build`, stood up the hugo site locally on 1313 and was able to browse the site content without issue.  I didn't see any other tests that I could run. 
> Add emacs to ide list w/ reference to tide-mode

- workshop/content/50-table-viewer/400-expose-table.md
Fixes issue #32  where constructor and super arguments are not the same, causing errors should the code be copy / pasted
> Fixes Documentation Code Typo

- workshop/content/30-hello-cdk/200-lambda.md
Previous link no longer working, I believe the new one is the most relevant equivalent
> Fix broken link to AWS Construct Library reference

- workshop/content/30-python/20-create-project/300-structure.md
- workshop/content/30-python/20-create-project/_index.md
- workshop/content/30-python/30-hello-cdk/200-lambda.md
- workshop/content/30-python/40-hit-counter/300-resources.md
- workshop/content/30-python/40-hit-counter/400-use.md
- workshop/content/30-python/40-hit-counter/600-permissions.md
- Changing `new AWS CDK TypeScript project` to `new AWS CDK Python project`
- Changing .ts to .py
- Changing npm to pip
> Fixing texts that mention TypeScript in Python workshop

- workshop/content/30-python/30-hello-cdk/200-lambda.md
Pip project name typo, plus a filename from typescript version of workshop carried over into the python one.
> Few typescript references in Python workshop

- workshop/content/30-python/40-hit-counter/300-resources.md
*Description of changes:* Initial step to install dynamodb construct library is duplicate from previous workshop step (200-handler.md).
Handler is defined as self._handler but all future steps reference the handler as only '.handler' fixing here will resolve issue in future steps (400-use.md & 600-permissions.md)
> Remove duplicate step & fix handler

- workshop/content/30-python/50-table-viewer/400-expose-table.md
*Description of changes:* Following lines need to be highlighted as they are different from the original definition of this file in both /workshop/content/30-python/40-hit-counter/300-resources.md and /workshop/content/30-python/40-hit-counter/600-permissions.md. This is since the addition of the table @property.
20 - change from table to self._table
32 - change from table to self.table
36 - change from table to self.table
> Highlighted lines to show changes in sample

- workshop/content/30-python/40-hit-counter/700-test.md
*Description of changes:* End of this chapter references packaging for npm. As this is the python learning path updating to pip and pypi.org.
> Fixed reference to NPM in Python learning path

- workshop/content/30-python/20-create-project/200-virtualenv.md
Windows usually is slash-agnostic, but this is one place where it actually requires the backslashes to work.
---
> Use backslashes in Windows virtualenv activation

- workshop/content/15-prerequisites/600-python.md
Might be better if the CDK would call `py` on Windows but as long as it's calling `python`, users need to make sure it's on the PATH.
---
> Add note about adding Python to PATH on Windows to Python prerequisites

- workshop/content/20-typescript/50-table-viewer/200-install.md
Fixes #45 
Removing the version pinned table-viewer. It's was pinned to 3.0.2 which requires old peer dependencies. 
`requires a peer of @aws-cdk/aws-apigateway@^0.38.0` 
This is no longer needed.
---
> Removing version pinned table-viewer, no longer needed

- workshop/content/20-typescript/50-table-viewer/400-expose-table.md
Fixes #83 
Correcting the DynamoDB syntax for https://cdkworkshop.com/20-typescript/50-table-viewer/400-expose-table.html 
---
> fixing issue with ddb syntax

- workshop/content/20-typescript/30-hello-cdk/200-lambda.md
Fixes #79  
Hugo renders the JS code in the markdown incorrectly if it's present after a list. I fixed this by adding a horizontal ruler as a workaround:
---
> Fixing indention

- workshop/content/20-typescript/50-table-viewer/400-expose-table.md
The wrong line is highlighted
Fixes # 
---
> fix: changed highlighted line in "Exposing our hit counter table" TS Workshop page

- workshop/content/20-typescript/40-hit-counter/300-resources.md
The formatting of `partitionKey` in 300-resources.md is inconsistent with the way that same code is presented in 400-expose-table.md.  This makes it difficult to find the code when you are asked to place a new entry after that code block in 400-expose-table.md.
I've expanded the hash across multiple line to maintain formatting consistency.
Fixes # 
---
> docs: Make formatting consistent with later versions of code

- workshop/content/20-typescript/40-hit-counter/100-api.md
- workshop/content/40-dotnet/40-hit-counter/100-api.md
In the "What's going on here?" section, the explanation of the type for the `Downstream` property is incorrect.  The letter "I" (for interface) appears to have been dropped.
I've corrected it for the TypeScript and .NET documentation.
Fixes # 
---
> docs: Correct explanation of type for 'Downstream' property

- workshop/content/20-typescript/30-hello-cdk/200-lambda.md
- workshop/content/20-typescript/40-hit-counter/300-resources.md
- workshop/content/30-python/30-hello-cdk/200-lambda.md
- workshop/content/30-python/40-hit-counter/300-resources.md
- workshop/content/40-dotnet/30-hello-cdk/200-lambda.md
- workshop/content/40-dotnet/40-hit-counter/300-resources.md
- workshop/content/50-java/30-hello-cdk/200-lambda.md
- workshop/content/50-java/40-hit-counter/300-resources.md
Converted markdown italics from `_underscore_` to the more standard `*single-asterisk*` format that is used in all other locations in the code.
Also attempted to fix the issue in the `200-lambda.md` files where the italics surrounding the "To read more about IDs..." text+link were not being honored when the markdown was being converted to HTML.  This resulted in the underscore characters showing on the cdkworkshop.com website and the inner text _not_ being italicized. My fix was to terminate the italicization before the link.
> docs: Fix markdown italics

- workshop/content/20-typescript/20-create-project/300-structure.md
- workshop/content/50-java/20-create-project/300-structure.md
The word 'instantiate' should have a 's' on the end to be grammatically correct in this context.  It looks like it has already been corrected for the Python and .NET versions of the workshop.
> docs: Minor grammar fix

- workshop/content/20-typescript/20-create-project/300-structure.md
Contents incorrectly shows that 'node' will be used to run the JavaScript version of the app.
The current iteration of this workshops uses 'npx' to run the TypeScript version of the app. So this commit updates the content to the actual content of cdk.json.
> docs: Update cdk.json content

- workshop/data/common.toml
update the cdk cli's version number to the latest one out there, currently
( maybe this version string can get dynamically updated by a lambda, whenever there is a new version out on npm... :-) )
---
> doc: update the cdk toolkit version

- workshop/content/20-typescript/30-hello-cdk/200-lambda.md
Tsc watch window no longer throws error at indicated point. Removing comment about error.
Fixes #92  
---
> fix: remove outdated blurb about error

- workshop/content/20-typescript/30-hello-cdk/200-lambda.md
Nodejs8.10 is no longer supported for creating or updating AWS Lambda functions.
---
> fix: Updating node version for typescript lambda example

- workshop/content/30-python/20-create-project/300-structure.md
Just fixing a typo in `/30-python/20-create-project/300-structure`
Fixes # couldn't bring myself to open a "bug" for this :)
---
> fix: minor typo in path at `python/create_project/structure`

- workshop/content/20-typescript/40-hit-counter/200-handler.md
> fix: Converted ES6 import to require

- workshop/content/20-typescript/40-hit-counter/300-resources.md
This isn't true: " (every DynamoDB
table must have a single partition key)"
> fix: misleading claim on dynamodb tables

- workshop/content/20-typescript/70-advanced-topics/100-construct-testing.md
- workshop/content/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.md
- workshop/content/20-typescript/70-advanced-topics/100-construct-testing/2000-validation-tests.md
- workshop/content/20-typescript/70-advanced-topics/100-construct-testing/_index.md
- workshop/content/20-typescript/70-advanced-topics/_index.md
This PR adds a new `Advanced Topics` section to the Typescript portion of the workshop. My idea here was to have an area where we can put topics that aren't necessary for the core workshop, but would still be interesting topics. Let me know if you think there is a better way of organizing this content or if you think it should just be merged into the existing sections.
I've also added an initial chapter on writing unit tests for constructs. The chapter uses the `HitCounter` construct that is created earlier in the workshop. It walks through writing different types of tests for this construct. 
> feat(testing): add testing guide to workshop

- .github/workflows/close-stale-issues.yml
- Sends a warning and then closes issues that haven't gotten a response in 2 years.
- Adds a closing-soon label to issues that have had the response-requested label for a week with no response.
- Sends a warning and then closes issues that have a closing-soon label and haven't had a response in 4 days.
---
> chore(repo): Add stale github action

- workshop/content/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.md
Adding lambda import in typescript/1000-assertion-test-100.md
Fixes #145 
---
> fix: TypeScript missing lambda import

- code/typescript/package-lock.json
Fixes security alert: https://github.com/aws-samples/aws-cdk-intro-workshop/network/alert/code/typescript/package-lock.json/bl/open
---
> chore: bump bl from 1.2.2 to 4.0.3 in /code/typescript

- workshop/content/20-typescript/30-hello-cdk/300-apigw.md
The lines to be highlighted were off by one. This shifts the group of highlighted lines down by one.
> fix: highlight proper lines in code example

- code/typescript/main-workshop/lib/cdk-workshop-stack.ts
Without exporting the CdkWorkshopStack class,
`npm run build` fails with:
```
lib/cdk-workshop-stack.ts(7,7): error TS6196: 'CdkWorkshopStack' is declared but never used.
```
---
> fix: make the main workshop TS code compile

- workshop/content/30-python/20-create-project/100-cdk-init.md
- workshop/content/30-python/20-create-project/200-virtualenv.md
- workshop/content/30-python/20-create-project/300-structure.md
related to: https://github.com/aws/aws-cdk/issues/9134
> fix: virtualenv directory `.env` to `.venv` for python workshop

- workshop/content/50-java/40-hit-counter/600-permissions.md
Fixes # 
There was a file called `HitCounter.java` and it was being referenced in the docs as `HitCounter.cs`.
This PR just changes the file type to the appropriate `.java`
---
> fix: java hitcounter file type typo

- workshop/content/20-typescript/70-advanced-topics/200-pipelines/_index.md
Fixes #203 
proccess -> process in `./workshop/content/20-typescript/70-advanced-topics/200-pipelines/_index.md`
---
> docs: fix typo in _index.md for TypeScript pipelines

- code/typescript/main-workshop/lib/cdk-workshop-stack.ts
- code/typescript/pipelines-workshop/lib/cdk-workshop-stack.ts
- code/typescript/tests-workshop/lib/cdk-workshop-stack.ts
- workshop/content/20-typescript/70-advanced-topics/200-pipelines/3000-new-pipeline.md
- workshop/content/20-typescript/70-advanced-topics/200-pipelines/4000-build-stage.md
- workshop/content/20-typescript/70-advanced-topics/200-pipelines/5000-test-actions.md
- workshop/content/40-dotnet/70-advanced-topics/100-pipelines/3000-new-pipeline.md
Fixed a couple of typos; `repoh` -> `repo` and `is` -> `id`.
---
> docs: Fix typos

- workshop/content/15-prerequisites/700-dotnet.md
Update to reflect .NET Core 3.1 is the base version needed.
---
> fix(net): update .NET prereq page for current minimum of .NETCore3.1

- workshop/content/40-dotnet/20-create-project/100-cdk-init.md
.NET "Create project directory" said "We will use cdk init to create a new TypeScript CDK project:". Changed to "We will use cdk init to create a new C# CDK project:"
Fixes # 
---
> chore: update language 100-cdk-init.md

- code/python/main-workshop/cdk-workshop/cdk-workshop_stack.py
- code/python/main-workshop/cdk-workshop/hitcounter.py
- code/python/pipelines-workshop/cdk-workshop/cdk-workshop_stack.py
- code/python/pipelines-workshop/cdk-workshop/hitcounter.py
- workshop/content/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.md
- workshop/content/20-typescript/70-advanced-topics/200-pipelines/5000-test-actions.md
- workshop/content/30-python/30-hello-cdk/300-apigw.md
- workshop/content/30-python/40-hit-counter/300-resources.md
- workshop/content/30-python/40-hit-counter/600-permissions.md
- workshop/content/30-python/50-table-viewer/300-add.md
`_lambda.Code.asset('path')` is deprecated method call on aws_cdk.aws_lambda 1.91.0 shown [here](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda/Code.html#aws_cdk.aws_lambda.Code.asset).
Fixes https://github.com/aws-samples/aws-cdk-intro-workshop/issues/197
---
> fix: replaced deprecated method call

- workshop/content/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.md
`inline` method is deprecated.
Fixes # 
---
> fix: TS: changed `inline` to `fromInline`

- workshop/content/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.md
With the correct format, it should be `{ Ref: "TestFunctionXXXXX" }` instead of `"TestFunctionXXXXX"`.
Fixes # 
---
> fix: format of "Variables:" was incorrect

- .gitignore
- code/typescript/main-workshop/bin/cdk-workshop.ts
- code/typescript/main-workshop/package-lock.json
- code/typescript/main-workshop/package.json
Upgrade CDK in the TypeScript sample code to 1.100.0.
This is necessary to address the `netmask` vulnerability GitHub is reporting.
---
> chore: upgrade CDK to 1.100.0

- workshop/content/20-typescript/40-hit-counter/600-permissions.md
- workshop/content/20-typescript/50-table-viewer/400-expose-table.md
Thank you for the workshop. There seems to be a little type miss.
It should be changed hitcounter's downstream function type `Function` to `IFunction`.
In this page the hitcounter's downstream function type is `Function`.
https://cdkworkshop.com/20-typescript/40-hit-counter/600-permissions.html
Fixes  https://github.com/aws-samples/aws-cdk-intro-workshop/issues/120
---
> fix: function type Function to IFunction

- cdkworkshop.com/pipeline.ts
Adds a Cloudwatch alarm notification to email on pipeline failures.
---
> feat: add event notification for pipeline failure

- .github/workflows/build-workshop-site.yml
This PR implements CI workflows that verify changes do not break builds.
GitHub Workflows:
- builds the workshop site
Fixes #259
---
> feat(CI): workflow for building site

- cdkworkshop.com/pipeline.ts
The pipeline build is failing after the conversion to CDKv2 and the new
pipelines API in the post-build phase:
```
[Container] 2021/11/01 11:43:11 Phase context status code:  Message:
[Container] 2021/11/01 11:43:11 Expanding base directory path: cdk.out
[Container] 2021/11/01 11:43:11 Assembling file list
[Container] 2021/11/01 11:43:11 Expanding cdk.out
[Container] 2021/11/01 11:43:11 Skipping invalid file path cdk.out
```
This is because the working directory for the post-build phase is the package
root, instead of the CDK root (./cdkworkshop.com).
---
> fix: pipeline build fails due to invalid file path

- workshop/content/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.md
- workshop/content/20-typescript/70-advanced-topics/100-construct-testing/_index.md
Updated the TypeScript Testing Constructs section of the workshop to use
the new @aws-cdk/assertions module
---
> feat(test-workshop): typescript tests now use assertions module

- workshop/content/30-python/70-advanced-topics/100-construct-testing/_index.md
This PR adds `aws-cdk.assertions` to the list of pip dependencies to install before writing CDK tests.
Fixes: https://github.com/aws/aws-cdk/issues/17310
---
> docs(python/advanced-topics/construct-testing) added `aws-cdk.assertions` to pip install command

- workshop/content/30-python/70-advanced-topics/200-pipelines/4000-build-stage.md
- workshop/content/30-python/70-advanced-topics/200-pipelines/5000-test-actions.md
Fixes # [309](https://github.com/aws-samples/aws-cdk-intro-workshop/issues/309)
The sample code [here](https://github.com/aws-samples/aws-cdk-intro-workshop/tree/master/code/python/pipelines-workshop) already referring to the right stack, however the workshop instruction is not up to date.
---
> fix: invalid reference to the stack

- workshop/content/30-python/50-table-viewer/300-add.md
- workshop/content/30-python/70-advanced-topics/200-pipelines/5000-test-actions.md
This PR updates uses of the python module `cdk_dynamo_table_viewer` with the correct name `cdk_dynamo_table_view`
ref: https://pypi.org/project/cdk-dynamo-table-view/
Fixes #414 
---
> fix(python docs): updated `cdk_dynamo_table_viewer` -> `cdk_dynamo_table_view`

- workshop/content/20-typescript/70-advanced-topics/200-pipelines/3000-new-pipeline.md
> fix: workshop says to install package present in aws-cdk-lib

- workshop/layouts/partials/menu-footer.html
The footer currently says `(c) 2020` only - updated it to say `(c) 2020-2022`
****
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).
> Update footer with the copyright year range

- workshop/content/30-python/70-advanced-topics/100-construct-testing/1000-assertion-test.md
- workshop/content/30-python/70-advanced-topics/100-construct-testing/2000-validation-tests.md
- workshop/content/30-python/70-advanced-topics/200-pipelines/1000-setting-up.md
- workshop/content/30-python/70-advanced-topics/200-pipelines/2000-create-repo.md
- workshop/content/30-python/70-advanced-topics/200-pipelines/3000-new-pipeline.md
- workshop/content/30-python/70-advanced-topics/200-pipelines/4000-build-stage.md
This PR contains small syntactical corrections for the Advanced Topics module of the python tutorial. It appears that some of it was copy/pasted from other iterations of the tutorial, and the steps as outlined don't work. This fixes a good portion of them. Below are the original errors that have been corrected:
1. All of the tests use a node JS runtime for the Lambda instead of a Python runtime.
1. Under "Getting started with pipelines/Create Pipeline Stack," the code includes `from pipeline_stage import WorkshopPipelineStage`. This dependency does not exist yet at this part in the tutorial
1. Under "Create repository/Deploy," the source instructs the user to enter `npx cdk deploy`. I think this might be copy/pasted from the TypeScript workshop and should be just `cdk deploy`
1. Under …
> fix: make syntactical corrections in python/advanced topics module.

- workshop/content/30-python/70-advanced-topics/200-pipelines/5000-test-actions.md
This PR contains a small correction for the Advanced Topics module of the Python tutorial. The step did not work as  it contained a typo: `self._hc_enpdoint = service.hc_endpoint => self._hc_endpoint = service.hc_endpoint`
---
> fix: cdk_workshop/pipeline_stage.py in Python/Advanced Topics/CDK Pipeline/Polish pipeline 

- workshop/layouts/partials/header.html
Fixes #448 
Replaced obsolete functions to build with the latest hugo.
---
> fix:  replace obsolete hugo functions

- workshop/content/20-typescript/70-advanced-topics/200-pipelines/5000-test-actions.md
- workshop/content/40-dotnet/70-advanced-topics/100-pipelines/5000-test-actions.md
Fixes #585 
Fixes highlighting of ENDPOINT_URL in Typescript and .NET workshops
* https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/5000-test-actions.html
* https://cdkworkshop.com/40-dotnet/70-advanced-topics/100-pipelines/5000-test-actions.html
---
> Fix highlighting in 'Polish Pipeline' step of TS and .NET workshops

- workshop/content/20-typescript/20-create-project/500-deploy.md
- workshop/content/30-python/20-create-project/500-deploy.md
- workshop/content/40-dotnet/20-create-project/500-deploy.md
- workshop/content/50-java/20-create-project/500-deploy.md
- workshop/content/60-go/20-create-project/500-deploy.md
Hi team,
These links are broken
they go to
> Fix link to AWS CLI configuration

- workshop/content/english/60-go/70-advanced-topics/200-pipelines/1000-setting-up.md
- workshop/content/english/60-go/70-advanced-topics/200-pipelines/5000-test-actions.md
During the workshop DevFest Strasbourg 2022, last Friday, with François Bouteruche and Olivier Leplus, I found 2 typos in the Go version of the workshop. So I updated the documentation.
Moreover, I performed all steps/chapters of the workshop, with the latest versions available on my MacOS (Catalina 10.15.7)
My versions tested are:
awscli (2.8.13 -> 2.9.0), six v1.16.0
with Go v1.19.3, node v19.1.0, c-ares v1.18.1, libnghttp2 v1.50
Kind regards,
David Aparicio, DataOps @ OVHcloud
> 📚 docs: typo fixes in the Go workshop

- workshop/content/english/30-python/30-hello-cdk/100-cleanup.md
Comma after Stack in aws_cdk import caused syntax error. Removed comma.
Fixes # 
---
> Removed unnecessary comma

- workshop/content/english/15-prerequisites/900-go.md
- workshop/content/japanese/15-prerequisites/900-go.md
Fixes #881 
In the english and japanese workshop the link to the go.dev web page contained a broken Markdown link syntax.
(go.dev)[https://go.dev/] instead of [go.dev](https://go.dev/)
---
> docs: fixed markdown syntax for link

- workshop/content/english/20-typescript/70-advanced-topics/200-pipelines/_index.md
Fixed a minor typo in the [_index.md](https://github.com/aws-samples/aws-cdk-intro-workshop/blob/master/workshop/content/english/20-typescript/70-advanced-topics/200-pipelines/_index.md) file.
Fixes #901 
---
> Fixed typo in _index.md [english][typescript]

- workshop/content/english/70-construct-hub/_index.md
- workshop/content/japanese/70-construct-hub/_index.md
The construct hub section consists only of one page and hence does not need a drop down menu.
Fixes #812 
---
> fix: removed unneccessary dropdown

- workshop/content/english/30-python/20-create-project/300-structure.md
There was a typo in the word "environment" - fixed it
> fix "environment" typo

- code/typescript/internal-constructs-workshop/construct-lib-repo/constructs/.gitattributes
- code/typescript/internal-constructs-workshop/construct-lib-repo/constructs/.gitignore
- code/typescript/internal-constructs-workshop/construct-lib-repo/constructs/.projen/deps.json
- code/typescript/internal-constructs-workshop/construct-lib-repo/constructs/.projen/files.json
- code/typescript/internal-constructs-workshop/construct-lib-repo/constructs/.projenrc.js
- code/typescript/internal-constructs-workshop/construct-lib-repo/constructs/package-lock.json
- code/typescript/internal-constructs-workshop/construct-lib-repo/constructs/package.json
- code/typescript/internal-constructs-workshop/construct-lib-repo/constructs/yarn.lock
- code/typescript/main-workshop/package-lock.json
- code/typescript/main-workshop/package.json
- code/typescript/pipelines-workshop/package-lock.json
- code/typescript/pipelines-workshop/package.json
- code/typescript/tests-workshop/package-lock.json
- code/typescript/tests-workshop/package.json
Fixes security vulnerability by updating Projen version in the projen package code
Fixes integration build by matching CDK CLI version with the package version, and also reverts `cdk-dynamo-table-viewer` construct [where it was previously missed](https://github.com/aws-samples/aws-cdk-intro-workshop/pull/1001)
---
> chore: update projen construct code dependencies

- workshop/content/english/20-typescript/50-table-viewer/200-install.md
- workshop/content/japanese/20-typescript/50-table-viewer/200-install.md
An old version of a dependency package ("cdk-dynamo-table-viewer") used Lambda runtime Node v12, which is no longer supported by AWS.
The dependency package already been updated with Node v18 (and AWS SDK v3) in order to avoid this limitation.
Update the workshop docs with the relevant newer release of cdk-dynamo-table-viewer - version 0.2.46
fixes #1060
> upgrade cdk-dynamo-table-viewer - in order to use Lambda runtime Node v18 (instead of v12)

- workshop/content/japanese/20-typescript/70-advanced-topics/200-pipelines/2000-create-repo.md
- workshop/content/japanese/30-python/70-advanced-topics/200-pipelines/2000-create-repo.md
- workshop/content/japanese/40-dotnet/70-advanced-topics/100-pipelines/2000-create-repo.md
- workshop/content/japanese/50-java/70-advanced-topics/100-pipelines/2000-create-repo.md
In the Japanese translation the default git branch in all variants (Typescript,  Python, Java, .NET) was still listed as `master`. Updated this to `main` to be in sync with the English version.
Please note: the updated pages contain an image still showing  `master`  in a drop down menu - let me know if you would like to have this updated, too. I have skipped this for the moment as the English version has same inconsistency.  
Links to these images:
* https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/repo-code.png
* https://cdkworkshop.com/ja/20-typescript/70-advanced-topics/200-pipelines/repo-code.png
Fixes #764
(and stays in conflict with #939 as this PR proposes a change from `main` to `master`. 
---
By submitting this pull request, I confirm that my contribution is …
> fix: replaced master with main

- code/python/pipelines-workshop/cdk_workshop/pipeline_stack.py
Per cdkworkshop.com, the branch is written as main not master. Updating to maintain consistency
Fixes # 
---
> Update pipeline_stack.py to reference the correct branch (main)

- workshop/content/english/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.md
Add mention of running build step after making changes in the final assertion test. Was wondering why my test didn't pass, until I realized I needed to build it first.
Fixes # 
---
> Add mention of running build step

- workshop/content/english/30-python/40-hit-counter/100-api.md
&nbsp;
Fixed small typo in [100-api.md](https://github.com/aws-samples/aws-cdk-intro-workshop/blob/master/workshop/content/english/30-python/40-hit-counter/100-api.md) file.
---
> Fix typo in 100-api.md[english][python]

- workshop/content/english/20-typescript/40-hit-counter/100-api.md
The current documentation implies we forward `props` to the `cdk.Construct` base class while the code does not.
This PR is an attempt to make the documentation better represent what the code does.
---
By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT-0 License](https://github.com/aws/mit-0/blob/master/MIT-0)
> Clarify arguments forwarded to base Construct class

- workshop/content/english/50-java/60-cleanups/_index.md
Since we have made a change in Table removal policy(.removalPolicy(RemovalPolicy.DESTROY)), we need to re-deploy the stack. Otherwise when we execute `cdk destroy` , the DynamoDb table will not be destroyed.
> Updated _index.md

- workshop/content/english/20-typescript/60-cleanups/_index.md
- workshop/content/english/30-python/60-cleanups/_index.md
- workshop/content/english/40-dotnet/60-cleanups/_index.md
- workshop/content/english/60-go/60-cleanups/_index.md
Fixes # 1131
Running through the TS sample, i followed to the letter and then didn't get my DB deleted after destroy. The docs could be improved with the suggestion of deploying prior to destroy...  checking the other languages, Java had this but none of the other languages. So i duplicated it's exact text for all other languages.
NOTE: Japanese still does not have this.
---
> fix: add deploy before destroy in all english docs
